import RowContainer from "@/components/RowContainer/RowContainer";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Website template</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>

        <RowContainer>
          <div className="col-start-2 col-end-4 laptop:col-end-8 desktop:col-end-14">
            <p className="">Container</p>
          </div>
        </RowContainer>
      </main>
    </>
  );
}
