import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import ButtonPrimary from "@/components/buttons/button-primary/button-primary";
import ButtonLink from "@/components/buttons/button-link/button-link";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <section className="hero bg-tertiary-50">
          <div className="row">
            <div className="col col--6">
              <h1 className="text-c-3xl heading text-quaternary-500 mb-8 max-w-[30rem]">
                Un mouvement de jeunesse{" "}
                <span className="text-secondary-500">pour tous</span>
              </h1>
              <p className="text-c-base text-quaternary-200 mb-10 max-w-[28rem]">
                Lorem ipsum dolor sit amet consectetur. A posuere tempus donec
                scelerisque ornare. Nam in tempor id convallis. Platea ut
                feugiat massa tempus malesuada.
              </p>
              <div className="button__container">
                <ButtonPrimary />
                <ButtonLink />
              </div>
            </div>
          </div>
        </section>
        <section className="main-informations">
          <div className="row">
            <div className="col col--10">
              <h2 className="text-c-2xl heading text-quaternary-500">
                Infos principales
              </h2>
            </div>
          </div>
        </section>
        <section className="latest-news bg-tertiary-50">
          <div className="row">
            <div className="col">
              <h2 className="text-c-2xl heading text-quaternary-500">
                Communications
              </h2>
            </div>
          </div>
        </section>
        <section className="latest-news">
          <div className="row">
            <div className="col">
              <h2 className="text-c-2xl heading text-quaternary-500">
                Viens nous rejoindre !
              </h2>
              <p className="text-c-base text-quaternary-200 mb-10 max-w-[28rem]">
                Lorem ipsum dolor sit amet consectetur. A posuere tempus donec
                scelerisque ornare. Nam in tempor id convallis. Platea ut
                feugiat massa tempus malesuada.
              </p>
              <h4 className="text-c-md heading text-quaternary-500">
                Le Patro, c'est...
              </h4>
            </div>
          </div>
        </section>
      </main>
    </>
  );
}
